- name: Get IIS-Config and Web.config File
  hosts: win
  gather_facts: true

  tasks:

  - name: Get IIS-Config and Web.config File
    ansible.windows.win_powershell:
      script: |
         # Get-WebApplication -Site "Default Web Site" | Select path, applicationPool, PhysicalPath | ConvertTo-Json
         #$webApplications = Get-WebApplication -Site "Default Web Site" | Select path, applicationPool, PhysicalPath | ConvertTo-Json | ConvertFrom-Json
         $webApplications = Get-WebApplication -Site "Default Web Site" | Select-Object path, applicationPool, PhysicalPath
         Write-Output $webApplications
         $IisServer = (hostname)
         New-PSDrive -Name Y -PSProvider FileSystem -Root \\Win19-DevOpsProd\Public_Share_Name\core-apps -Verbose

         foreach( $webApp in $webApplications ) {
             # Copy Web.Config From IIS Server to Web Repo    
             $targetPath = "Y:\\$IisServer\\Default Web Site\\$($webApp.path.substring(1))"
             New-Item -Path $targetPath -ItemType Directory -Verbose -Force
             Copy-Item "$($webApp.PhysicalPath)\\Web.config" -Destination "$targetPath" -Verbose -Force
    
             # Create Configuration File for Web Application 
             $iisWebAppConfigJson = @{
                 'Site' = 'Default Web Site'
                 'WebAppName' = "$($webApp.path.substring(1))"
                 'applicationPool' = "$($webApp.applicationPool)"
                 'PhysicalPath' = "$($webApp.PhysicalPath)"
             }
    
             $iisWebAppConfigVariable = $iisWebAppConfigJson | ConvertTo-Json | Out-File "$targetPath\\iis-webapp-config.json" -Encoding ASCII -Verbose 

         }

         Get-IISSite | Select-Object Name, State | ConvertTo-Json | Out-File "Y:\\$IisServer\\iis-server-config.json" -Encoding ASCII -Verbose 
